trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '3e3bebed-d23f-4e91-8bc7-7636382225c8'
  imageRepository: 'botskynodejsrepo'
  containerRegistry: 'testcontainerregistrydemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build, scan and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    
    # Replace with manual installation steps for Trivy
    - script: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.tar.gz
        tar zxvf trivy_0.49.1_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin
      displayName: 'Manually Install Trivy v0.49.1'
    
    - script: |
        trivy --version
      displayName: 'Verify Trivy Installation'  
      
    - script: |
        trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Scan image with Trivy'
      
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
